apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  generation: 1
  labels:
    app: ssc
  name: ssc
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: ssc
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ssc
    spec:
      containers:
      - image: ghcr.io/ericaabrahms/sbom-scorecard-website:main
        imagePullPolicy: Always
        name: sbom-scorecard-website
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kubernetes.digitalocean.com/load-balancer-id: c54cf5d6-9170-42d1-a4e9-3eb2844b694a
    service.beta.kubernetes.io/do-loadbalancer-protocol: "https"
    service.beta.kubernetes.io/do-loadbalancer-certificate-id: "aa0a6503-5c54-4d3e-bfb7-767f1054f61f"
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  labels:
    app: ssc
  name: ssc
  namespace: default
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.245.237.147
  clusterIPs:
  - 10.245.237.147
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31994
    port: 443
    protocol: TCP
    targetPort: 8000
  selector:
    app: ssc
  sessionAffinity: None
  type: LoadBalancer